extends: capitalization
message: "'%s' should be in sentence case"
level: warning
scope: heading
# $title, $sentence, $lower, $upper, or a pattern.
match: $sentence
exceptions:
  - ACLs
  - Amazon Aurora
  - Amazon Web Services
  - APIs
  - Aiven
  - Apache
  - Boot
  - Business
  - BYOA
  - Cassandra
  - ClickHouse
  - Connect
  - Dashboards
  - Datadog
  - Debezium
  - Dev
  - Disaster Recovery
  - Docker
  - Dynamic Disk Sizing
  - Elasticsearch
  - European Union
  - Flink
  - GitHub
  - Go
  - Google BigQuery
  - Google Cloud Platform
  - Google Cloud Platform Marketplace
  - Google Cloud Storage
  - Google Cloud SQL
  - Google Data Studio
  - Grafana
  - Hobbyist
  - HowTo
  - InfluxDB
  - InnoDB
  - IPsec
  - Java
  - Kafdrop
  - Kafka
  - Karapace
  - Kpow
  - Kubernetes
  - M3
  - Microsoft Azure
  - MirrorMaker
  - MongoDB
  - MySQL
  - NodeJS
  - OpenSearch
  - Operator
  - Pagila
  - pgAdmin
  - PgBouncer
  - PostgreSQL
  - Postman
  - Premium
  - Prometheus
  - Provectus
  - Python
  - Redis
  - reStructuredText
  - Schema Registry
  - Simple Authentication and Security Layer
  - Snowflake
  - Sphinx
  - Spring
  - SQL Server
  - Startup
  - TaskManager
  - Telegraf
  - Terraform
  - TimescaleDB
  - Transport Layer Security
  - United States
  - VPC
  - Workbench
  - ZooKeeper
