name: "LinkCheck - All files"

on:
  schedule:
    - cron: "0 5 * * 2"
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: LinkCheck
        uses: mathiasvr/command-output@v1
        id: tests
        with:
          run: make linkcheck

      - name: Create an issue
        if: failure()
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.date.outputs.today }}
          body: |
            ${{ steps.tests.outputs.stderr }}

            - [ ] Have a meeting with UX team
            - [ ] Check the dashboard

          labels: |
            bug
