name: "LinkCheck - All files"

on:
  schedule:
    - cron: "0 5 * * 2"
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: LinkCheck
        run: make linkcheck
      - name: Create Issue
        if: failure() # OR Check a bool variable you create and toggle as needed
        uses: JasonEtco/create-an-issue@masterenv:GITHUB_TOKEN:${{ secrets.GITHUB_TOKEN }}
