name: "LinkCheck - All files"

on:
  schedule:
    - cron: "0 5 * * 2"
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: LinkCheck
        uses: mathiasvr/command-output@v1
        id: broken_link
        with:
          run: |
            make linkcheck

      - name: Echo plan output to a file
        if: failure()
        run: |
          echo ${{ steps.broken_link.outputs.stdout }} > ${GITHUB_WORKSPACE}/plan.txt
          out=$(cat plan.txt | grep -E "broken")
          out=$(echo -n $out | tail -c 60000)
          echo "::set-output name=BROKEN_LINKS::$out"

      - name: Create an issue
        if: failure()
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: test
          body: ${{ steps.broken_link.outputs.BROKEN_LINKS }}
