name: Linting
on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:

jobs:
  prose:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      # 2020-08-12 The default branch of vale-action is `reviewdog`, which
      # defaults to using the latest version of `vale`
      # If we want a specific version, use `version:` in the `with` clause below
      uses: errata-ai/vale-action@reviewdog
      with:
        files: '["index.rst", "docs"]'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

