name: TestLaysa
on:
  push:
    branches:
      - master
    tags:
      - "**"
  pull_request:

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Find changed .rst files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ "${file: -4}" == ".rst" ]
              then
                var="$var $file"
            fi
          done 
          echo "$var"
          make files="$var" linkcheck-changed-files
